apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: druid
  name: druid-mm-autoscaler-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets","statefulsets/scale"]
  verbs: ["get", "list", "create", "patch"]
